name: Playwright Tests
on:
  issue_comment:
    types: [created]

jobs:
  visual_regression:
    # ラベル「VisualRegression」と EE 生成完了の PR comment を参照する
    if: contains(github.event.pull_request.labels.*.name, 'VisualRegression') == true && ${{ github.event.issue.pull_request }} && contains(github.event.comment.html_url, '/pull/' && startsWith(github.event.comment.body, 'お寿司')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
